import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from '@/components/ui/sidebar';

const roboto = Roboto(
  {
    weight: ['100', '300', '400', '500', '700', '900'], 
    style: ['normal', 'italic'],  
    subsets: ['latin'], 
    variable: "--font-roboto",
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} >
      <body
        className={`${roboto.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <SidebarProvider>
          {children}
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default RootLayout;